version: '3.7'

services:

  eventstore:
    container_name: eventstoredb
    image: eventstore/eventstore:release-5.0.10
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_INSECURE_TCP: 'true'

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-CU23-ubuntu-20.04
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Inforigami1

  ravendb:
    container_name: ravendb
    image: ravendb/ravendb:7.1-ubuntu-latest
    ports:
      - '8080:8080'
      - '8081:8081'
    environment:
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Setup_Mode: None
      RAVEN_ServerUrl: http://0.0.0.0:8080
      RAVEN_Security_UnsecuredAccessAllowed: 'PublicNetwork'
