name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Docker Compose will handle these, no need to define here unless you want GitHub managed containers
      # Leaving empty because we'll start them manually via docker compose

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        # Leave out dotnet-version to pick version from your csproj files
        include-prerelease: false

    - name: Start services
      run: docker compose -f docker-compose.yml up -d

    - name: Wait for services to be ready
      run: |
        # Wait for RavenDB
        until curl -s http://localhost:8080; do
          echo "Waiting for RavenDB..."
          sleep 5
        done
        # Wait for SQL Server
        until docker exec sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Inforigami1 -Q "SELECT 1"; do
          echo "Waiting for SQL Server..."
          sleep 5
        done
        # Wait for EventStoreDB
        until curl -s http://localhost:2113; do
          echo "Waiting for EventStoreDB..."
          sleep 5
        done

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Stop Docker Compose services
      if: always()
      run: docker compose -f docker-compose.yml down

    - name: Push package to nuget.org
      if: github.ref == 'refs/heads/master'
      env:
        NugetOrgApiKey: ${{ secrets.NugetOrgApiKey }}
      run: pwsh ./PushPackage.ps1